print('Введите целое кол-во пингвинов от 1 до 9:')
penguin_quantity = int(input())
print('   _~_    ' * penguin_quantity)
print('  (0 0)   ' * penguin_quantity)
print(' /  V  \\  ' * penguin_quantity)
print('/(  _  )\\ ' * penguin_quantity)
print('  ^^ ^^   ' * penguin_quantity)
